services:
  tts-bot:
    build: .
    container_name: tts_bot_container
    restart: always
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"